name: hello-world

on: push
jobs:

  build:

    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2

      - name: Hexlet project check
        uses: hexlet/project-action@release
      - run: make say-hello